### ISSUE TITLE
What do you mean by "copy the parameters"

### ISSUE THREAD

**Issue by Devilben4** [arifyaman/faceDepthAI#1]
Hello,

I can't make your code work, i don't know what you mean by "copy the parameters"

**Comment by arifyaman** [comment]
@Devilben4 
First, you can just run it without copying/pasting anything, and check in unreal engine if your depth frames are in a good position with your face, most likely it will be fine. But if they don't match nicely you can tweak/play around the params below 

[create_single_sample_and_display.py](https://github.com/arifyaman/faceDepthAI/blob/master/face_mesh/create_single_sample_and_display.py)

```
# Parameters for DepthMapProcessor
depth_map_params = {
    'scale_factor': 0.2,                   # Scale factor for depth map values probably no need to play around, it is configured for Iphone15
    'target_dims': (360, 640),             # Target dimensions for the final depth map
    'face_scale_factors': (1, 1.15),       # Scale factors for width and height only for face area
    'margin': (0, -20)                     # Margin for translating the face area
}

# Camera translation and rotation parameters
camera_params = {
    'translation_vector': (0, 0, 0),            # Translation vector for the camera
    'rotation_angles': np.radians([-15, 0, 0])  # Rotation angles (in radians) for the camera
}
```
run&check if the mask fits with your face nicely, then you can paste these params into 
[convert_images_to_depth_maps.py](https://github.com/arifyaman/faceDepthAI/blob/master/face_mesh/convert_images_to_depth_maps.py)

you can check in the video from this part to understand https://youtu.be/fsi7dAxHAuk?si=v9bDdknxli3Ua_86&t=722

**Comment by arifyaman** [comment]
I believe it helped if you still have questions you can open another issue ^^
